trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ASPNETCore-WebAPI-Sample/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'azure-pipelines.yml'

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: imageRepository
    value: 'bestrong-web-api'
  - name: tag
    value: '$(Build.BuildId)'
  - name: appServiceName
    value: 'bestrong-app-service'
  - name: resourceGroupName
    value: 'bestrong-rg'
  - name: acrName
    value: 'bestrongacr'

stages:
  - stage: Validate
    displayName: 'Validate Application'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        steps:
          - checkout: self
          
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
              tags: '$(tag)'
              buildContext: $(System.DefaultWorkingDirectory)
  
  - stage: Deploy
    displayName: 'Deploy Application'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployImage
        displayName: 'Build and Deploy Image'
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'Azure Login and Push Docker Image'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                docker build -t $(acrName).azurecr.io/$(imageRepository):$(tag) -t $(acrName).azurecr.io/$(imageRepository):latest .
                
                az acr login --name $(acrName)
                
                docker push $(acrName).azurecr.io/$(imageRepository):$(tag)
                docker push $(acrName).azurecr.io/$(imageRepository):latest
          
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroupName)
              imageName: '$(acrName).azurecr.io/$(imageRepository):$(tag)' 