trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: terraform-variables

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker image
    jobs:
      - job: DockerJob
        displayName: Build & Push
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: |
              echo "Logging into ACR..."
              echo $(DOCKER_PASSWORD) | docker login bestrong1acr1.azurecr.io -u $(DOCKER_USERNAME) --password-stdin

              echo "Building Docker image..."
              docker build -t bestrong1acr1.azurecr.io/bestrong-web-api:latest .

              echo "Pushing Docker image..."
              docker push bestrong1acr1.azurecr.io/bestrong-web-api:latest
            displayName: Docker Login, Build & Push
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: BuildAndPush
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployJob
        displayName: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: envFile
            displayName: 'Download .env file'
            inputs:
              secureFile: '.env'

          - script: |
              echo "Loading environment variables from .env file..."
              export $(cat $(envFile.secureFilePath) | grep -v '^#' | xargs)

              echo "Logging into Azure..."
              az login --service-principal \
                -u $TF_VAR_client_id \
                -p $TF_VAR_client_secret \
                --tenant $TF_VAR_tenant_id

              echo "Deploying to App Service..."
              az webapp config container set \
                --name $(APP_SERVICE_NAME) \
                --resource-group $(RESOURCE_GROUP_NAME) \
                --docker-custom-image-name bestrong1acr1.azurecr.io/bestrong-web-api:latest \
                --docker-registry-server-url https://bestrong1acr1.azurecr.io \
                --docker-registry-server-user $(DOCKER_USERNAME) \
                --docker-registry-server-password $(DOCKER_PASSWORD)

              az webapp config set \
                --name $(APP_SERVICE_NAME) \
                --resource-group $(RESOURCE_GROUP_NAME) \
                --linux-fx-version "DOCKER|bestrong1acr1.azurecr.io/bestrong-web-api:latest" \
                --always-on true \
                --http20-enabled true

              az webapp cors add \
                --name $(APP_SERVICE_NAME) \
                --resource-group $(RESOURCE_GROUP_NAME) \
                --allowed-origins "*"

              az webapp restart \
                --name $(APP_SERVICE_NAME) \
                --resource-group $(RESOURCE_GROUP_NAME)

              echo "Deployment successfully completed!"
            displayName: Deploy to App Service