trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: terraform-variables

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker image
    jobs:
      - job: DockerJob
        displayName: Build & Push
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: |
              echo "Logging into ACR..."
              echo $(DOCKER_PASSWORD) | docker login bestrong1acr1.azurecr.io -u $(DOCKER_USERNAME) --password-stdin

              echo "Building Docker image..."
              docker build -t bestrong1acr1.azurecr.io/bestrong-web-api:latest .

              echo "Pushing Docker image..."
              docker push bestrong1acr1.azurecr.io/bestrong-web-api:latest
            displayName: Docker Login, Build & Push