trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'bestrong-docker-acr'
  imageRepository: 'bestrong-web-api'
  containerRegistry: 'bestrong-acr-connection'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker image'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              dockerfile: $(dockerfilePath)
              repository: $(imageRepository)
              containerRegistry: $(containerRegistry)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(containerRegistry)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to App Service'
            inputs:
              azureSubscription: 'bestrong-rg-connection'
              appName: 'bestrong-app-service-bs2'
              resourceGroupName: 'bestrong-rg'
              containers: 'bestrong1acr1.azurecr.io/bestrong-web-api:latest'