trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: terraform-variables

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildAndPushJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: DockerInstaller@0
            displayName: Install Docker

          - task: Docker@2
            displayName: Docker Login
            inputs:
              command: login
              containerRegistry: ''
              repository: ''
              dockerRegistryEndpoint: ''
              username: $(DOCKER_USERNAME)
              password: $(DOCKER_PASSWORD)

          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              command: buildAndPush
              repository: bestrong-web-api
              dockerfile: $(Build.SourcesDirectory)/Dockerfile
              tags: |
                latest
              containerRegistry: ''
              repository: bestrong1acr1.azurecr.io/bestrong-web-api
              addPipelineData: false
              addBaseImageData: false
              arguments: '--no-cache'
              buildContext: '$(Build.SourcesDirectory)'

